# Generated by Django 6.0.1 on 2026-02-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(blank=True, max_length=10, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=60, null=True)),
                ('module_code', models.CharField(blank=True, max_length=10, null=True)),
                ('submodule_code', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=60, null=True)),
                ('icon', models.CharField(blank=True, max_length=600, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engine_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=20)),
                ('module_name', models.CharField(blank=True, max_length=60, null=True)),
                ('url', models.CharField(blank=True, max_length=60, null=True)),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engine_module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineSubmodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(blank=True, max_length=10, null=True)),
                ('submodule_code', models.CharField(max_length=20)),
                ('submodule_name', models.CharField(blank=True, max_length=60, null=True)),
                ('url', models.CharField(blank=True, max_length=60, null=True)),
                ('icon', models.CharField(blank=True, max_length=600, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engine_submodule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.IntegerField(blank=True, null=True)),
                ('setting_name', models.CharField(blank=True, max_length=100, null=True)),
                ('module_code', models.CharField(blank=True, max_length=45, null=True)),
                ('submodule_code', models.CharField(blank=True, max_length=45, null=True)),
                ('activity_code', models.CharField(blank=True, max_length=45, null=True)),
                ('setting_value', models.CharField(blank=True, max_length=45, null=True)),
                ('setting_value2', models.CharField(blank=True, max_length=255, null=True)),
                ('used_for', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
    ]
