# Generated by Django 6.0.1 on 2026-02-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('username', models.CharField(db_collation='utf8mb3_general_ci', max_length=20)),
                ('password', models.CharField(db_collation='utf8mb3_general_ci', max_length=128)),
                ('email', models.CharField(db_collation='utf8mb3_general_ci', max_length=128)),
                ('activkey', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('superuser', models.IntegerField()),
                ('status', models.IntegerField()),
                ('usertype', models.IntegerField()),
                ('employee_code', models.CharField(db_collation='utf8mb3_general_ci', max_length=128)),
                ('company_code', models.CharField(blank=True, db_collation='latin1_bin', max_length=45, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('lastvisiton', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
