# Generated by Django 6.0.1 on 2026-02-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('company_address', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=256, null=True)),
                ('company_email', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('company_phone', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=15, null=True)),
                ('company_mobile', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=15, null=True)),
                ('company_fax', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('company_contactperson', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('company_country', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('company_state', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('company_currency', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=60, null=True)),
                ('company_registrationnumber', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='company_registrationNumber', max_length=45, null=True)),
                ('company_gstnumber', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='company_GSTNumber', max_length=45, null=True, unique=True)),
                ('company_timezone', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=60, null=True)),
                ('company_logo', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=60, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Financialyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financialyear_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('financialyear_startyear', models.CharField(blank=True, max_length=45, null=True)),
                ('financialyear_endyear', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financialyear',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('usertype_name', models.CharField(blank=True, max_length=45, null=True)),
                ('financialyear', models.IntegerField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=45, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usertype',
                'managed': False,
            },
        ),
    ]
