# Generated by Django 6.0.1 on 2026-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_company_financialyear_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True, unique=True)),
                ('company_code', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_firstname', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_middlename', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_lastname', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_joiningdate', models.DateField(blank=True, null=True)),
                ('employee_qualification', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_totalexperiance', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('financialyear_id', models.IntegerField(blank=True, null=True)),
                ('department_code', models.CharField(blank=True, max_length=100, null=True)),
                ('designation_id', models.IntegerField(blank=True, null=True)),
                ('usertype_id', models.IntegerField(blank=True, null=True)),
                ('division_code', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_gender', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_comment='1=>Male,2=>Female', max_length=10, null=True)),
                ('employee_address1', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=256, null=True)),
                ('employee_address2', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=256, null=True)),
                ('employee_country', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_state', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_city', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_pincode', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_phone', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=15, null=True)),
                ('employee_mobile', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=15, null=True)),
                ('employee_email', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('employee_photo', models.CharField(blank=True, max_length=1550, null=True)),
                ('employee_status', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_comment='1=>existing,2=>resigned,3=>terminated', max_length=45, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=256, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
