# Generated by Django 6.0.2 on 2026-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('city_name', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=45)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('country_name', models.CharField(max_length=255)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('associate_code', models.IntegerField(blank=True, null=True)),
                ('partner_code', models.CharField(blank=True, max_length=45, null=True)),
                ('company_code', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('email_id', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('password', models.CharField(db_collation='utf8mb3_general_ci', max_length=128)),
                ('company_contactperson', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('contact_number', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=256, null=True)),
                ('city_code', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('country_code', models.CharField(blank=True, max_length=45, null=True)),
                ('gstin', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('referral_code', models.TextField(blank=True, db_column='Referral_code', null=True)),
                ('refferral_status', models.IntegerField(blank=True, db_column='Refferral_status', null=True)),
                ('desigation', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_id', models.IntegerField(blank=True, null=True)),
                ('associate_code', models.IntegerField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('contact_no', models.TextField(db_collation='utf8mb3_unicode_ci')),
                ('visit_for', models.TextField(db_collation='utf8mb3_unicode_ci')),
                ('follow_up_type', models.TextField(db_collation='utf8mb3_unicode_ci')),
                ('customer_status', models.TextField(blank=True, db_collation='utf8mb3_unicode_ci', null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('type', models.TextField(blank=True, db_collation='utf8mb3_unicode_ci', null=True)),
                ('note', models.TextField(blank=True, db_collation='utf8mb3_unicode_ci', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('partner_code', models.CharField(blank=True, max_length=45, null=True)),
                ('associate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_followup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('state_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
    ]
