# Generated by Django 6.0.2 on 2026-02-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_cities_countries_customer_customerfollowup_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_code', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('mobile_no', models.BigIntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('month', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'associates',
                'managed': False,
            },
        ),
    ]
