# Generated by Django 6.0.2 on 2026-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_associates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_code', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('projection', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('theater_name', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('theater_address', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=256, null=True)),
                ('city_code', models.CharField(blank=True, max_length=45, null=True)),
                ('district_code', models.CharField(blank=True, max_length=45, null=True)),
                ('state_code', models.CharField(blank=True, max_length=45, null=True)),
                ('seating_capacity', models.IntegerField(blank=True, db_column='Seating_Capacity', null=True)),
                ('cinema_type', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('cinema_category', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('rate', models.IntegerField(blank=True, db_column='Rate', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=255, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cinema_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CinemalistMysql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_field', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Sr#', max_length=255, null=True)),
                ('web_code', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Web_Code', max_length=255, null=True)),
                ('projection', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Projection', max_length=255, null=True)),
                ('theater_name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Theater Name', max_length=255, null=True)),
                ('theater_address', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Theater Address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='City', max_length=255, null=True)),
                ('district', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='District', max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='State', max_length=255, null=True)),
                ('seating_capacity', models.FloatField(blank=True, db_column='Seating_Capacity', null=True)),
                ('cinema_category', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Cinema_Category', max_length=255, null=True)),
                ('grade', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Grade', max_length=255, null=True)),
                ('rate', models.FloatField(blank=True, db_column='Rate', null=True)),
                ('image', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Image', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cinemalist_mysql',
                'managed': False,
            },
        ),
    ]
