# Generated by Django 6.0.2 on 2026-03-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_cinemalist_cinemalistmysql'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abcdcinemalist',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('web_code', models.CharField(blank=True, db_column='Web_code', max_length=100, null=True)),
                ('projection', models.TextField(blank=True, db_column='Projection', null=True)),
                ('cinema_chain', models.TextField(blank=True, db_column='Cinema_Chain', null=True)),
                ('theatre_name', models.TextField(blank=True, db_column='Theatre_Name', null=True)),
                ('theatre_address', models.TextField(blank=True, db_column='Theatre_Address', null=True)),
                ('pincode', models.TextField(blank=True, db_column='Pincode', null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.TextField(blank=True, db_column='District', null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('seating_capacity', models.TextField(blank=True, db_column='Seating_Capacity', null=True)),
                ('cinema_type', models.TextField(blank=True, db_column='Cinema_Type', null=True)),
                ('cinema_category', models.TextField(blank=True, db_column='Cinema_Category', null=True)),
                ('image', models.FloatField(blank=True, db_column='Image', null=True)),
                ('rate_10sec_week', models.FloatField(blank=True, null=True)),
                ('rate_per_sec_per_week', models.FloatField(blank=True, null=True)),
                ('bb_rate_10sec_week', models.FloatField(blank=True, db_column='BB_rate_10sec_week', null=True)),
                ('bb_rate_per_sec_per_week', models.FloatField(blank=True, db_column='BB_rate_per_sec_per_week', null=True)),
            ],
            options={
                'db_table': 'abcdcinemalist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('p_id', models.CharField(max_length=45)),
                ('web_code', models.CharField(blank=True, max_length=45, null=True)),
                ('media_name', models.CharField(max_length=500)),
                ('theatre_address', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=200)),
                ('seats_number', models.CharField(max_length=45)),
                ('projection', models.CharField(max_length=45)),
                ('rate', models.FloatField()),
                ('customer_id', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=45)),
                ('district', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('campaign_category', models.CharField(max_length=45)),
                ('associate_code', models.IntegerField(blank=True, null=True)),
                ('base_rate_10secweek', models.IntegerField(blank=True, null=True)),
                ('bb_rate_10secweek', models.IntegerField(blank=True, null=True)),
                ('base_rate_10secweek_0', models.IntegerField(blank=True, null=True)),
                ('bb_rate_10secweek_0', models.IntegerField(blank=True, null=True)),
                ('rate_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_code', models.TextField(blank=True, null=True)),
                ('projection', models.CharField(blank=True, max_length=100, null=True)),
                ('cinema_chain', models.CharField(blank=True, max_length=200, null=True)),
                ('theatre_name', models.CharField(blank=True, max_length=100, null=True)),
                ('theatre_address', models.CharField(blank=True, max_length=500, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('seating_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('cinema_type', models.CharField(blank=True, max_length=20, null=True)),
                ('cinema_category', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=250, null=True)),
                ('rate_10sec_week', models.IntegerField(blank=True, null=True)),
                ('rate_per_sec_per_week', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_cinema',
                'managed': False,
            },
        ),
    ]
