# Generated by Django 6.0.2 on 2026-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_code', models.IntegerField(blank=True, null=True)),
                ('associate_code', models.IntegerField(blank=True, null=True)),
                ('screen_number', models.IntegerField(blank=True, null=True)),
                ('media_name', models.TextField(blank=True, null=True)),
                ('projection', models.TextField(blank=True, null=True)),
                ('number_seats', models.IntegerField(blank=True, null=True)),
                ('city_code', models.CharField(blank=True, max_length=45, null=True)),
                ('state_code', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('ads_in_second', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('ad_type', models.TextField(blank=True, db_column='ad_Type', null=True)),
                ('ad_position', models.TextField(blank=True, null=True)),
                ('total_sreen_rate', models.IntegerField(blank=True, null=True)),
                ('gross_total', models.IntegerField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('discount_total', models.IntegerField(blank=True, null=True)),
                ('censor_certificate', models.TextField(blank=True, null=True)),
                ('censor_cc', models.IntegerField(blank=True, db_column='censor_CC', null=True)),
                ('gst', models.FloatField(blank=True, null=True)),
                ('total_taxable_amount', models.FloatField(blank=True, null=True)),
                ('payment_mode', models.TextField(blank=True, null=True)),
                ('payment_status', models.TextField(blank=True, null=True)),
                ('coupon_code', models.TextField(blank=True, null=True)),
                ('reference_code', models.TextField(blank=True, null=True)),
                ('customize_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('campaign_status', models.TextField(blank=True, null=True)),
                ('campaign_start_date', models.TextField(blank=True, null=True)),
                ('campaign_end_date', models.TextField(blank=True, null=True)),
                ('total_payable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invoice', models.TextField(blank=True, null=True)),
                ('remaining_amount', models.FloatField(blank=True, null=True)),
                ('paid', models.CharField(blank=True, max_length=45, null=True)),
                ('transaction_id_check_no', models.TextField(blank=True, db_column='transaction_id/check_no', null=True)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('campaign_name', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=45, null=True)),
                ('campaign_category', models.TextField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoupenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('associate_code', models.IntegerField(blank=True, null=True)),
                ('coupen_discount', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('generate_coupen', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=15, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupen_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('coupen_type', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('coupen_code', models.CharField(blank=True, max_length=45, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('coupen_status', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoviesliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('releasing_date', models.DateField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movieslider_image',
                'managed': False,
            },
        ),
    ]
