# Generated by Django 6.0.2 on 2026-03-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_bookcampaign_coupenrequest_coupens_moviesliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, db_column='cart_Id', max_length=45, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=45, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=45, null=True)),
                ('cart_id', models.CharField(blank=True, max_length=45, null=True)),
                ('screen_id', models.IntegerField(blank=True, null=True)),
                ('media_name', models.CharField(blank=True, max_length=500, null=True)),
                ('web_code', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('district', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('theatre_address', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('seats_number', models.IntegerField(blank=True, null=True)),
                ('projection', models.CharField(blank=True, max_length=45, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('base_rate_10secweek', models.IntegerField(blank=True, null=True)),
                ('bb_rate_10secweek', models.IntegerField(blank=True, null=True)),
                ('base_rate_10secweek_0', models.IntegerField(blank=True, null=True)),
                ('bb_rate_10secweek_0', models.IntegerField(blank=True, null=True)),
                ('grand_total', models.IntegerField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=45, null=True)),
                ('rate_type', models.IntegerField(blank=True, null=True)),
                ('campaign_category', models.CharField(blank=True, max_length=45, null=True)),
                ('associate_code', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_cart_item',
                'managed': False,
            },
        ),
    ]
