# Generated by Django 6.0.2 on 2026-03-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenlistingNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.TextField(blank=True, null=True)),
                ('webcode', models.TextField(blank=True, null=True)),
                ('projection', models.TextField(blank=True, null=True)),
                ('cinema_chain', models.TextField(blank=True, null=True)),
                ('theatre_name', models.TextField(blank=True, null=True)),
                ('theatre_address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('seating_capacity', models.TextField(blank=True, null=True)),
                ('cinema_type', models.TextField(blank=True, null=True)),
                ('cinema_category', models.TextField(blank=True, null=True)),
                ('base_rate_10sec_week', models.TextField(blank=True, null=True)),
                ('bb_rate_10sec_week', models.TextField(blank=True, null=True)),
                ('partner_base_rate_10sec_week', models.TextField(blank=True, null=True)),
                ('partner_bb_rate_10sec_week', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'screenlisting_new',
                'managed': False,
            },
        ),
    ]
