# Generated by Django 6.0.2 on 2026-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_screenlistingnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screensfro', models.IntegerField(blank=True, null=True)),
                ('screesto', models.IntegerField(blank=True, null=True)),
                ('weeksfron', models.IntegerField(blank=True, null=True)),
                ('weeksto', models.IntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'discount_rates',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Abcdcinemalist',
        ),
    ]
