# Generated by Django 6.0.2 on 2026-03-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_discountrates_delete_abcdcinemalist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adlengths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_value', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'adlengths',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_value', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'weeks',
                'managed': False,
            },
        ),
    ]
