# Generated by Django 6.0.2 on 2026-03-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_adlengths_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generateotp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, max_length=45, null=True)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'generateotp',
                'managed': False,
            },
        ),
    ]
