# Generated by Django 6.0.2 on 2026-03-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_generateotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype_id', models.IntegerField(blank=True, null=True)),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('submodule_id', models.IntegerField(blank=True, null=True)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('e_read', models.CharField(blank=True, max_length=10, null=True)),
                ('e_write', models.CharField(blank=True, max_length=10, null=True)),
                ('e_update', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'permissions',
                'managed': False,
            },
        ),
    ]
