# Generated by Django 6.0.4 on 2026-04-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=45, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=45, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=45, null=True)),
                ('rate_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ad_length', models.CharField(blank=True, max_length=45, null=True)),
                ('weeks', models.IntegerField(blank=True, null=True)),
                ('ad_position', models.CharField(blank=True, max_length=50, null=True)),
                ('ad_type', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('question1', models.CharField(blank=True, max_length=10, null=True)),
                ('question2', models.CharField(blank=True, max_length=10, null=True)),
                ('manual_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manual_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_cart_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerCustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, db_column='cart_Id', max_length=45, null=True)),
                ('partner_code', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=45, null=True)),
                ('partner_customer_cartcol', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partner_customer_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerCustomerCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, max_length=45, null=True)),
                ('cart_id', models.CharField(blank=True, max_length=45, null=True)),
                ('screen_id', models.IntegerField(blank=True, null=True)),
                ('media_name', models.CharField(blank=True, max_length=500, null=True)),
                ('web_code', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('district', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('theatre_address', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('seats_number', models.IntegerField(blank=True, null=True)),
                ('projection', models.CharField(blank=True, max_length=45, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('base_rate_10secweek', models.IntegerField(blank=True, null=True)),
                ('bb_rate_10secweek', models.IntegerField(blank=True, null=True)),
                ('base_rate_10secweek_0', models.IntegerField(blank=True, null=True)),
                ('bb_rate_10secweek_0', models.IntegerField(blank=True, null=True)),
                ('grand_total', models.IntegerField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=45, null=True)),
                ('rate_type', models.IntegerField(blank=True, null=True)),
                ('campaign_category', models.CharField(blank=True, max_length=45, null=True)),
                ('partner_code', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partner_customer_cart_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerQuotationCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partner_quotation_counter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ro_counter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profile_images',
                'managed': False,
            },
        ),
    ]
